# desc "Create app on developer portal"
# lane :create_app do
#   create_app_online #produce
# end

default_platform(:ios)

platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end
  
  desc "Signing process"
  lane :signing do
    sync_code_signing #match

    Mapping = Action,lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    update_code_signing_settings(
      use_automatic_signing: false,
      path: ENV["PROJECT_PATH"],
      profile_name: ENV['MATCH_APP_IDENTIFIER']
    )
  end

  desc "Build binary"
  lane :build do
    signing
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Release binary"
  lane :release do
    build
  end

end

# bundle exec fastlane match nuke 

# [!] Please run `fastlane match nuke [type], allowed values: development, distribution and enterprise. For the 'adhoc' type, please use 'distribution' instead.
# @Mew2king